import { BankJSON } from "../models/QuestionBankModel"

export const allQuestions: BankJSON = {
    "capitalQuestions": {
        "Alabama": "Montgomery",
        "Alaska": "Juneau",
        "Arizona": "Phoenix",
        "Arkansas": "Little Rock",
        "California": "Sacramento",
        "Colorado": "Denver",
        "Connecticut": "Hartford",
        "Delaware": "Dover",
        "Florida": "Tallahassee",
        "Georgia": "Atlanta",
        "Hawaii": "Honolulu",
        "Idaho": "Boise",
        "Illinois": "Springfield",
        "Indiana": "Indianapolis",
        "Iowa": "Des Moines",
        "Kansas": "Topeka",
        "Kentucky": "Frankfort",
        "Louisiana": "Baton Rouge",
        "Maine": "Augusta",
        "Maryland": "Annapolis",
        "Massachusetts": "Boston",
        "Michigan": "Lansing",
        "Minnesota": "Saint Paul",
        "Mississippi": "Jackson",
        "Missouri": "Jefferson City",
        "Montana": "Helena",
        "Nebraska": "Lincoln",
        "Nevada": "Carson City",
        "New Hampshire": "Concord",
        "New Jersey": "Trenton",
        "New Mexico": "Santa Fe",
        "New York": "Albany",
        "North Carolina": "Raleigh",
        "North Dakota": "Bismarck",
        "Ohio": "Columbus",
        "Oklahoma": "Oklahoma City",
        "Oregon": "Salem",
        "Pennsylvania": "Harrisburg",
        "Rhode Island": "Providence",
        "South Carolina": "Columbia",
        "South Dakota": "Pierre",
        "Tennessee": "Nashville",
        "Texas": "Austin",
        "Utah": "Salt Lake City",
        "Vermont": "Montpelier",
        "Virginia": "Richmond",
        "Washington": "Olympia",
        "District of Columbia": "None",
        "West Virginia": "Charleston",
        "Wisconsin": "Madison",
        "Wyoming": "Cheyenne"
    },
    "flowerQuestions": {
        "Alabama": "Camellia",
        "Alaska": "Forget-Me-Not",
        "Arizona": "Saguaro Cactus Blossom",
        "Arkansas": "Apple Blossom",
        "California": "Golden Poppy",
        "Colorado": "Rocky Mountain Columbine",
        "Connecticut": "Mountain Laurel",
        "Delaware": "Peach Blossom",
        "Florida": "Orange Blossom",
        "Georgia": "Cherokee Rose",
        "Hawaii": "Yellow Hibiscus",
        "Idaho": "Syringa",
        "Illinois": "Violet",
        "Indiana": "Peony",
        "Iowa": "Wild Rose",
        "Kansas": "Sunflower",
        "Kentucky": "Goldenrod",
        "Louisiana": "Magnolia",
        "Maine": "White Pine Cone and Tassel",
        "Maryland": "Black-Eyed Susan",
        "Massachusetts": "Mayflower",
        "Michigan": "Apple Blossom",
        "Minnesota": "Pink and White Lady’s Slipper",
        "Mississippi": "Magnolia",
        "Missouri": "Hawthorn",
        "Montana": "Bitterroot",
        "Nebraska": "Goldenrod",
        "Nevada": "Sagebrush",
        "New Hampshire": "Purple Lilac",
        "New Jersey": "Violet",
        "New Mexico": "Yucca Flower",
        "New York": "Rose",
        "North Carolina": "Dogwood",
        "North Dakota": "Wild Prairie Rose",
        "Ohio": "Scarlet Carnation",
        "Oklahoma": "Oklahoma Rose",
        "Oregon": "Oregon Grape",
        "Pennsylvania": "Mountain Laurel",
        "Rhode Island": "Violet",
        "South Carolina": "Yellow Jessamine",
        "South Dakota": "Pasque Flower",
        "Tennessee": "Iris",
        "Texas": "Bluebonnet",
        "Utah": "Sego Lily",
        "Vermont": "Red Clover",
        "Virginia": "American Dogwood",
        "Washington": "Coast Rhododendron",
        "District of Columbia": "American Beauty Rose",
        "West Virginia": "Rhododendron",
        "Wisconsin": "Wood Violet",
        "Wyoming": "Indian Paintbrush"
    },
    "abbreviationQuestions": {
        "Alabama": "AL",
        "Alaska": "AK",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "Florida": "FL",
        "Georgia": "GA",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Pennsylvania": "PA",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Washington": "WA",
        "District of Columbia": "DC",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY"
    },
    "dateQuestions": {
        "Alabama": "1819",
        "Alaska": "1959",
        "Arizona": "1812",
        "Arkansas": "1836",
        "California": "1850",
        "Colorado": "1876",
        "Connecticut": "1788",
        "Delaware": "1787",
        "Florida": "1845",
        "Georgia": "1788",
        "Hawaii": "1959",
        "Idaho": "1890",
        "Illinois": "1818",
        "Indiana": "1816",
        "Iowa": "1846",
        "Kansas": "1861",
        "Kentucky": "1792",
        "Louisiana": "1812",
        "Maine": "1820",
        "Maryland": "1788",
        "Massachusetts": "1788",
        "Michigan": "1837",
        "Minnesota": "1858",
        "Mississippi": "1817",
        "Missouri": "1821",
        "Montana": "1889",
        "Nebraska": "1867",
        "Nevada": "1864",
        "New Hampshire": "1788",
        "New Jersey": "1787",
        "New Mexico": "1912",
        "New York": "1788",
        "North Carolina": "1789",
        "North Dakota": "1889",
        "Ohio": "1803",
        "Oklahoma": "1907",
        "Oregon": "1859",
        "Pennsylvania": "1787",
        "Rhode Island": "1790",
        "South Carolina": "1788",
        "South Dakota": "1889",
        "Tennessee": "1796",
        "Texas": "1845",
        "Utah": "1896",
        "Vermont": "1791",
        "Virginia": "1788",
        "Washington": "1889",
        "District of Columbia": "1790",
        "West Virginia": "1863",
        "Wisconsin": "1848",
        "Wyoming": "1890"
    }
};