import { BankJSON } from "../models/QuestionBank"

export const allQuestions: BankJSON = {
    "capitalQuestions": {
        "Alabama": "Montgomery",
        "Alaska": "Juneau",
        "Arizona": "Phoenix",
        "Arkansas": "Little Rock",
        "California": "Sacramento",
        "Colorado": "Denver",
        "Connecticut": "Hartford",
        "Delaware": "Dover",
        "Florida": "Tallahassee",
        "Georgia": "Atlanta",
        "Hawaii": "Honolulu",
        "Idaho": "Boise",
        "Illinois": "Springfield",
        "Indiana": "Indianapolis",
        "Iowa": "Des Moines",
        "Kansas": "Topeka",
        "Kentucky": "Frankfort",
        "Louisiana": "Baton Rouge",
        "Maine": "Augusta",
        "Maryland": "Annapolis",
        "Massachusetts": "Boston",
        "Michigan": "Lansing",
        "Minnesota": "Saint Paul",
        "Mississippi": "Jackson",
        "Missouri": "Jefferson City",
        "Montana": "Helena",
        "Nebraska": "Lincoln",
        "Nevada": "Carson City",
        "New Hampshire": "Concord",
        "New Jersey": "Trenton",
        "New Mexico": "Santa Fe",
        "New York": "Albany",
        "North Carolina": "Raleigh",
        "North Dakota": "Bismarck",
        "Ohio": "Columbus",
        "Oklahoma": "Oklahoma City",
        "Oregon": "Salem",
        "Pennsylvania": "Harrisburg",
        "Rhode Island": "Providence",
        "South Carolina": "Columbia",
        "South Dakota": "Pierre",
        "Tennessee": "Nashville",
        "Texas": "Austin",
        "Utah": "Salt Lake City",
        "Vermont": "Montpelier",
        "Virginia": "Richmond",
        "Washington": "Olympia",
        "West Virginia": "Charleston",
        "Wisconsin": "Madison",
        "Wyoming": "Cheyenne"
    },
    "flowerQuestions": {
        "Alabama": "alabama flower",
        "Alaska": "alaska flower",
        "Arizona": "arizona flower",
        "Arkansas": "arkansas flower",
        "California": "california flower",
        "Colorado": "colorado flower",
        "Connecticut": "connecticut flower",
        "Delaware": "delaware flower",
        "Florida": "florida flower",
        "Georgia": "georgia flower",
        "Hawaii": "hawaii flower",
        "Idaho": "idaho flower",
        "Illinois": "illinois flower",
        "Indiana": "indiana flower",
        "Iowa": "iowa flower",
        "Kansas": "kansas flower",
        "Kentucky": "kentucky flower",
        "Louisiana": "louisiana flower",
        "Maine": "maine flower",
        "Maryland": "maryland flower",
        "Massachusetts": "massachusetts flower",
        "Michigan": "michigan flower",
        "Minnesota": "minnesota flower",
        "Mississippi": "mississippi flower",
        "Missouri": "missouri flower",
        "Montana": "montana flower",
        "Nebraska": "nebraska flower",
        "Nevada": "nevada flower",
        "New Hampshire": "new hampshire flower",
        "New Jersey": "new jersey flower",
        "New Mexico": "new mexico flower",
        "New York": "new york flower",
        "North Carolina": "north carolina flower",
        "North Dakota": "north dakota flower",
        "Ohio": "ohio flower",
        "Oklahoma": "oklahoma flower",
        "Oregon": "oregon flower",
        "Pennsylvania": "pennsylvania flower",
        "Rhode Island": "rhode island flower",
        "South Carolina": "south carolina flower",
        "South Dakota": "south dakota flower",
        "Tennessee": "tennessee flower",
        "Texas": "texas flower",
        "Utah": "utah flower",
        "Vermont": "vermont flower",
        "Virginia": "virginia flower",
        "Washington": "washington flower",
        "West Virginia": "west virginia flower",
        "Wisconsin": "wisconsin flower",
        "Wyoming": "wyoming flower"
    },
    "abbreviationQuestions": {
        "Alabama": "AL",
        "Alaska": "AK",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "Florida": "FL",
        "Georgia": "GA",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Pennsylvania": "PA",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Washington": "WA",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY"
    }
};